feat: generate NFT metadata in memory
decentraland/atlas-server pull request #27
Opened 2021-02-22 15:11 UTC by cazala

The purpose of this PR is to stop hitting the marketplace subgraph to return metadata for parcels/estates, and instead generate all of the `NFT` objects while building the `Tile` objects on start up., and then serving them from memory.

In order to do so, instead of returning just `Tile[]`, the `api` component now returns `{ tiles: Tile[], parcels: NFT[], estates: NFT[] }`. Also the `map` component now has three records: `parcels`, `estates` and `tokens`, which give easy access to all the `NFT` by using the newly added methods `getParcel(x, y)`, `getEstate(estateId)` and `getToken(contractAddress, tokenId)`

2021-02-23 17:35 UTC, cazala commented
rebased

2021-02-25 19:47 UTC, nachomazzara commented on src/modules/api/component.ts
>  const tileFields = `{
should this be `parcelFields` as we are calling `ParcelFragment` the type?

2021-02-25 19:55 UTC, nachomazzara commented on src/modules/api/component.ts
>      // The following piece adds tiles from updated Estates. This is necessary only for an Estate that get listed or delisted on sale, since that doesn't chagne the lastUpdatedAt property of a Parcel.
Typo `chagne`

2021-02-25 20:18 UTC, nachomazzara commented on src/modules/map/component.ts
> +  function addParcels(newParcels: NFT[], oldParcels: Record<string, NFT>) {
should we need to add a blank here?

2021-02-25 20:19 UTC, nachomazzara requested changes
Excellent @cazala. Just minor comments

2021-02-25 22:58 UTC, cazala commented
Thanks for the review @nachomazzara :) I addressed the feedback

2021-02-26 00:43 UTC, merged